#-----------------------------------------------------------------------------
#  NEXTCLOUD.YML
#  =============
#     This requires TRAEFIK to be already running
#
#     See the video  : https://www.youtube.com/watch?v=A_TxxzOlDUc
#     Files based on : https://tech.aufomm.com/deploy-nextcloud-with-docker-and-traefik/
#
#     Access nextcloud with       https://nextcloud.girdglen.com
#     Access traefik monitor with https://traefik.girdglen.com
#     Lets Encrypt certificate stored in ~/docker/traefik/data/acme.json
#
#-----------------------------------------------------------------------------

version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE          
      - MYSQL_USER=$MYSQL_USER                  
      - MYSQL_PASSWORD=$MYSQL_PASSWORD          
      - MYSQL_INITDB_SKIP_TZINFO=1 

  redis:
    image: redis:latest
    restart: always
    networks:
      - default
    volumes:
      - redis:/var/lib/redis
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  nextcloud:
    depends_on:
      - redis
      - db
    image: nextcloud:stable 
    container_name: nextcloud
    volumes:
      - ${DOCKER_REMOTE}/nextcloud/app:/var/www/html
      - ${DOCKER_REMOTE}/nextcloud/data:/var/www/html/data
    networks:
      - t2_proxy
      - default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.$DOMAINNAME`)"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
      - "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}


networks:
  t2_proxy:
    external: true
    
volumes:
  nextcloud-db-data:
    name: nextcloud-db-data
  redis:
    name: nextcloud-redis
